{{- if .Values.networkPolicy.enabled }}
apiVersion: {{ include "infra-operator.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "infra-operator.fullname" . }}
  namespace: {{ include "infra-operator.namespace" . }}
  labels:
    {{- include "infra-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "infra-operator.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
