{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "infra-operator.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "infra-operator.fullname" . }}
  namespace: {{ include "infra-operator.namespace" . }}
  labels:
    {{- include "infra-operator.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "infra-operator.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
{{- end }}
