{{- if and .Values.aws.staticCredentials.enabled .Values.aws.staticCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.aws.staticCredentials.secretName }}
  labels:
    {{- include "infra-operator.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.aws.staticCredentials.accessKeyIDKey }}: {{ .Values.aws.staticCredentials.accessKeyID | quote }}
  {{ .Values.aws.staticCredentials.secretAccessKeyKey }}: {{ .Values.aws.staticCredentials.secretAccessKey | quote }}
  {{- if .Values.aws.staticCredentials.sessionToken }}
  {{ .Values.aws.staticCredentials.sessionTokenKey }}: {{ .Values.aws.staticCredentials.sessionToken | quote }}
  {{- end }}
{{- end }}
