{{- if and .Values.webhooks.enabled .Values.webhooks.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "infra-operator.webhookCertName" . }}
  namespace: {{ include "infra-operator.namespace" . }}
  labels:
    {{- include "infra-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "infra-operator.webhookServiceName" . }}.{{ include "infra-operator.namespace" . }}.svc
  - {{ include "infra-operator.webhookServiceName" . }}.{{ include "infra-operator.namespace" . }}.svc.cluster.local
  issuerRef:
    {{- toYaml .Values.webhooks.certManager.issuerRef | nindent 4 }}
  secretName: {{ include "infra-operator.webhookCertName" . }}
  {{- if .Values.webhooks.certManager.duration }}
  duration: {{ .Values.webhooks.certManager.duration }}
  {{- end }}
  {{- if .Values.webhooks.certManager.renewBefore }}
  renewBefore: {{ .Values.webhooks.certManager.renewBefore }}
  {{- end }}
{{- end }}
