apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-operator-controller-manager
  namespace: infra-operator-system
  annotations:
    # For IRSA (IAM Roles for Service Accounts) in EKS
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/infra-operator-role
