---
# Certificate for webhook server
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infra-operator-serving-cert
  namespace: iop-system
spec:
  dnsNames:
  - infra-operator-webhook-service.iop-system.svc
  - infra-operator-webhook-service.iop-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: infra-operator-selfsigned-issuer
  secretName: webhook-server-cert
